/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MainFrame.Create.Expences;

import DatabaseConnection.myConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author berendfuchs
 */
public class Expences extends javax.swing.JFrame {

    Connection con;
    PreparedStatement pst = null;
    Statement st;
    ResultSet rs;
    
    int mousepX;
    int mousepY;
    public Expences() {
        initComponents();
    }
    
    Object[] row = new Object[5];

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
//    private void saveInvoiceData(){
//        /*
//        Insert Invoice data into database
//        */
//        
//        for (int i = 0; i < jTable1.getRowCount(); i++) {
//            //z+=Double.parseDouble(jTable1.getValueAt(i, 3).toString());
//            String productFromJTable = jTable1.getValueAt(i, 0).toString();
//            String qtyFromJTable = jTable1.getValueAt(i, 1).toString();
//            String amountFromJTable = jTable1.getValueAt(i, 2).toString();
//            String totalFromJTable = jTable1.getValueAt(i, 3).toString();
//            try{
//                 theQuery("INSERT INTO `Invoices`(`ReferenceNumber`, `CustomerName`, `BillingAddress`, `ShippingAddress`, `DueDate`, `DateCreated`,"
//                         + " `product`, `qty`, `amount`, `total`, `status`) VALUES ('"+jLabelInvoiceNumber.getText()+"',"
//                         + "'"+jComboBoxCustomer.getSelectedItem().toString()+"','"+BillingAddress+"','"+ShippingAddress+"',"
//                         + "'"+((JTextField)jDateChooserDueDate.getDateEditor().getUiComponent()).getText()+"','"+((JTextField)jDateChooserInvoiceDate.getDateEditor().getUiComponent()).getText()+"',"
//                         + "'"+productFromJTable+"','"+qtyFromJTable+"','"+amountFromJTable+"','"+totalFromJTable+"','"+jComboBoxStatus.getSelectedItem().toString()+"')");
//             }
//             catch(Exception ex){}
//        }
//    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jDateChooserInvoiceDate = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jButtonADD = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jTextFieldAmount = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jButtonRemove = new javax.swing.JButton();
        jButtonUpdate = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jButtonSave = new javax.swing.JButton();
        jButtonClear = new javax.swing.JButton();
        jButtonPrint = new javax.swing.JButton();
        jTextFieldQTY = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(46, 204, 113));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("X");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 0, -1, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Expence");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, -1, -1));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("-");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 0, -1, -1));

        jPanel2.setBackground(new java.awt.Color(44, 62, 80));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jDateChooserInvoiceDate.setDateFormatString("yyyy-MM-dd");
        jPanel2.add(jDateChooserInvoiceDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 156, -1));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Expence date");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PRODUCT", "QTY", "AMOUNT", "TOTAL"
            }
        )
        {public boolean isCellEditable(int row, int column){return false;}}
    );
    jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            jTable1MouseClicked(evt);
        }
    });
    jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyPressed(java.awt.event.KeyEvent evt) {
            jTable1KeyPressed(evt);
        }
    });
    jScrollPane1.setViewportView(jTable1);

    jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 286, 930, 220));

    jLabel11.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
    jLabel11.setForeground(new java.awt.Color(255, 255, 255));
    jLabel11.setText("Total");
    jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 512, -1, -1));

    jButtonADD.setText("ADD");
    jButtonADD.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButtonADDActionPerformed(evt);
        }
    });
    jPanel2.add(jButtonADD, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

    jLabel15.setForeground(new java.awt.Color(255, 255, 255));
    jLabel15.setText("AMOUNT");
    jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));
    jPanel2.add(jTextFieldAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 223, -1));

    jLabel16.setForeground(new java.awt.Color(255, 255, 255));
    jLabel16.setText("QTY");
    jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

    jButtonRemove.setText("Remove");
    jButtonRemove.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButtonRemoveActionPerformed(evt);
        }
    });
    jPanel2.add(jButtonRemove, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, -1, -1));

    jButtonUpdate.setText("Update");
    jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButtonUpdateActionPerformed(evt);
        }
    });
    jPanel2.add(jButtonUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, -1, -1));

    jLabel14.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
    jLabel14.setForeground(new java.awt.Color(255, 255, 255));
    jLabel14.setText("N$ 0.00");
    jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 512, -1, -1));

    jButtonSave.setText("Save");
    jButtonSave.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButtonSaveActionPerformed(evt);
        }
    });
    jPanel2.add(jButtonSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, -1, -1));

    jButtonClear.setText("Email");
    jPanel2.add(jButtonClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, -1, -1));

    jButtonPrint.setText("Print");
    jPanel2.add(jButtonPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

    jTextFieldQTY.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusLost(java.awt.event.FocusEvent evt) {
            jTextFieldQTYFocusLost(evt);
        }
    });
    jPanel2.add(jTextFieldQTY, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 223, -1));

    jLabel17.setForeground(new java.awt.Color(255, 255, 255));
    jLabel17.setText("NAME");
    jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

    jTextFieldName.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusLost(java.awt.event.FocusEvent evt) {
            jTextFieldNameFocusLost(evt);
        }
    });
    jPanel2.add(jTextFieldName, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 223, -1));

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE))
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        int X = evt.getXOnScreen();
        int Y = evt.getYOnScreen();

        this.setLocation(X-mousepX, Y-mousepY);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        mousepX = evt.getX();
        mousepY = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // display selected JTable row data

        // get selected row index
        int rowIndex = jTable1.getSelectedRow();
        jTextFieldName.setText((String) jTable1.getValueAt(rowIndex, 0));
        jTextFieldQTY.setText((String) jTable1.getValueAt(rowIndex, 1));
        jTextFieldAmount.setText(jTable1.getValueAt(rowIndex, 2).toString());

        boolean a = jTable1.isEditing();

        if(a==true){
            JOptionPane.showMessageDialog(null, "Please update the selected row from the textfields");
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTable1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyPressed

    }//GEN-LAST:event_jTable1KeyPressed

    private void jButtonADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonADDActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

        /*
        NEW Variables
        */
        String Name = jTextFieldName.getText();
        int QTY = Integer.parseInt(jTextFieldQTY.getText());
        double amount = Double.parseDouble(jTextFieldAmount.getText());
        double total = QTY * amount;

        
            row[0] = Name;
            row[1] = QTY;
            row[2] = amount;
            row[3] = total;

            model.addRow(row);

            double z = 0;
            for (int i = 0; i < jTable1.getRowCount(); i++) {
                z+=Double.parseDouble(jTable1.getValueAt(i, 3).toString());
            }
            z = z*100;
            z = (double)((int) z);
            z = z /100;
            jLabel14.setText("N$ "+z);
            //iTax = String.format("N$ %.2f", itemcost[25] / 100);
        
    }//GEN-LAST:event_jButtonADDActionPerformed

    private void jButtonRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoveActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        int i = jTable1.getSelectedRow();
        if (i >= 0) {
            model.removeRow(i);
        } else {
            JOptionPane.showMessageDialog(rootPane, model);
        }
        double z = 0;
        for (int y = 0; y < jTable1.getRowCount(); y++) {
            z+=Double.parseDouble(jTable1.getValueAt(y, 3).toString());
        }
        z = z*100;
        z = (double)((int) z);
        z = z /100;
        jLabel14.setText("N$ "+z);
    }//GEN-LAST:event_jButtonRemoveActionPerformed

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

        int i = jTable1.getSelectedRow();

        if (i>=0) {
            model.setValueAt(jTextFieldName.getText(), i, 0);
            model.setValueAt(jTextFieldQTY.getText(), i, 1);
            model.setValueAt(jTextFieldAmount.getText(), i, 2);
            model.setValueAt(Double.parseDouble(jTextFieldQTY.getText()) * Double.parseDouble(jTextFieldAmount.getText()), i, 3);
        } else {
            JOptionPane.showMessageDialog(rootPane, model);
        }
        double z = 0;
        for (int y = 0; y < jTable1.getRowCount(); y++) {
            z+=Double.parseDouble(jTable1.getValueAt(y, 3).toString());
        }
        z = z*100;
        z = (double)((int) z);
        z = z /100;
        jLabel14.setText("N$ "+z);
    }//GEN-LAST:event_jButtonUpdateActionPerformed

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
//        saveExpence();
        this.dispose();
    }//GEN-LAST:event_jButtonSaveActionPerformed

    private void jTextFieldQTYFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldQTYFocusLost
//
//        try {
//            Connection connection = myConnection.getConnection();
//            st = connection.createStatement();
//            String s = "SELECT * FROM `products` WHERE `productname` LIKE  '%"+productName+"%'";
//            rs = st.executeQuery(s);
//            while(rs.next()){
//                String amount = rs.getString("sellingprice");
//                jTextFieldAmount.setText(amount);
//            }
//        } catch (SQLException e) {
//
//        }
    }//GEN-LAST:event_jTextFieldQTYFocusLost

    private void jTextFieldNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldNameFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNameFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Expences.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Expences.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Expences.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Expences.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Expences().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonADD;
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonPrint;
    private javax.swing.JButton jButtonRemove;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JButton jButtonUpdate;
    private com.toedter.calendar.JDateChooser jDateChooserInvoiceDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldAmount;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldQTY;
    // End of variables declaration//GEN-END:variables
}
