/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MainFrame.Create.customer;

import DatabaseConnection.myConnection;
import Login.loginForm;
import java.awt.CardLayout;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author berendfuchs
 */
public final class newCustomer extends javax.swing.JFrame {

    /**
     * Creates new form newCustomer
     */
    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    Statement st;
    
    int mousepX;
    int mousepY;
    
    
    public newCustomer() {
        initComponents();
        updateCityCombo();
        salesRep();
    }
    
        private void updateCityCombo(){
        try{
            con = DriverManager.getConnection("jdbc:mysql://192.168.8.158:3306/BargainDatabase","Berend", "kidcoltv6");
            st = con.createStatement();
            String s = "select * from cities";
            rs = st.executeQuery(s);
              while(rs.next())
              {
                  jComboBoxCity.addItem(rs.getString(2));
                  jComboBoxCity1.addItem(rs.getString(2));
              }
          }catch(Exception e){
              JOptionPane.showMessageDialog(null, "ERROR");
          }
        }
        
        Color textColor = new Color(153,153,153);
    
        String salesRepVariable = "";
        
        public void salesRep(){
            
            //SELECT * FROM `userLoggedIn` WHERE `id` = 0

        Connection con = myConnection.getConnection();
        PreparedStatement ps;
        ResultSet rs;
        
        try {
            ps = con.prepareStatement("SELECT * FROM `userLoggedIn` WHERE `id` = 0");
            rs = ps.executeQuery();
            
            if(rs.next()){
                //Get current user id
                salesRepVariable = rs.getString("log");
                jLabel38.setText(salesRepVariable);
                
            } else {
                JOptionPane.showMessageDialog(null, "Please Enter correct credentials");
            }
        } catch (SQLException ex) {
            Logger.getLogger(loginForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jButtonAddressInfo = new javax.swing.JButton();
        jButtonPaymentSettings = new javax.swing.JButton();
        jButtonAdditionalInfo = new javax.swing.JButton();
        jButtonJobInfo = new javax.swing.JButton();
        cardframe = new javax.swing.JPanel();
        jPanelAddressInfo = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldCompanyName = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldFirstName = new javax.swing.JTextField();
        jComboBoxTitle = new javax.swing.JComboBox<>();
        jTextFieldMidelName = new javax.swing.JTextField();
        jTextFieldLastName = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldJobTitle = new javax.swing.JTextField();
        jComboBoxContactInfo1 = new javax.swing.JComboBox<>();
        jTextFieldContactInfo1 = new javax.swing.JTextField();
        jTextFieldContactInfoPhone = new javax.swing.JTextField();
        jTextFieldContactInfoFax = new javax.swing.JTextField();
        jTextFieldContactInfoAlternativeContact = new javax.swing.JTextField();
        jTextFieldContactInfoAlternativePhone = new javax.swing.JTextField();
        jTextFieldContactInfoEmail = new javax.swing.JTextField();
        jPanelAddressDetails = new javax.swing.JPanel();
        jTextFieldPOBox = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextFieldZip = new javax.swing.JTextField();
        jTextFieldRegion = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jComboBoxCity = new javax.swing.JComboBox<>();
        jTextFieldStreetName = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jTextFieldHouseNumber = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jTextFieldHouseNumber1 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jTextFieldStreetName1 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jComboBoxCity1 = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        jTextFieldRegion1 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jTextFieldZip1 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jTextFieldPOBox1 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jPanelPaymentSettings = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jTextFieldCompanyName1 = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jTextFieldCreditLimit = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jComboBoxPeferredDeliveryMethod = new javax.swing.JComboBox<>();
        jLabel43 = new javax.swing.JLabel();
        jComboBoxPeferredPAYMENTMETHOD = new javax.swing.JComboBox<>();
        jLabel34 = new javax.swing.JLabel();
        jTextFieldCreditCardNo = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jTextFieldCVV = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        jTextFieldCreditCardAddress = new javax.swing.JTextField();
        jYearChooser1 = new com.toedter.calendar.JYearChooser();
        jLabel46 = new javax.swing.JLabel();
        jTextFieldCreditCardZip = new javax.swing.JTextField();
        jLabel47 = new javax.swing.JLabel();
        jTextFieldNameOnCard = new javax.swing.JTextField();
        jMonthChooser1 = new javax.swing.JComboBox<>();
        jPanelAdditionalInfo = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanelJobInfo = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldOpeningBalance = new javax.swing.JTextField();
        jTextFieldCustomerName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButtonCancel = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(44, 62, 80));
        jPanel2.setLayout(null);

        jButtonAddressInfo.setBackground(new java.awt.Color(102, 102, 255));
        jButtonAddressInfo.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jButtonAddressInfo.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAddressInfo.setText("Address Info");
        jButtonAddressInfo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonAddressInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddressInfoActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonAddressInfo);
        jButtonAddressInfo.setBounds(20, 120, 180, 70);

        jButtonPaymentSettings.setBackground(new java.awt.Color(102, 102, 255));
        jButtonPaymentSettings.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jButtonPaymentSettings.setForeground(new java.awt.Color(255, 255, 255));
        jButtonPaymentSettings.setText("Payment Settings");
        jButtonPaymentSettings.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonPaymentSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPaymentSettingsActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonPaymentSettings);
        jButtonPaymentSettings.setBounds(20, 190, 180, 70);

        jButtonAdditionalInfo.setBackground(new java.awt.Color(102, 102, 255));
        jButtonAdditionalInfo.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jButtonAdditionalInfo.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAdditionalInfo.setText("Additional Info");
        jButtonAdditionalInfo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonAdditionalInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdditionalInfoActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonAdditionalInfo);
        jButtonAdditionalInfo.setBounds(20, 260, 180, 70);

        jButtonJobInfo.setBackground(new java.awt.Color(102, 102, 255));
        jButtonJobInfo.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jButtonJobInfo.setForeground(new java.awt.Color(255, 255, 255));
        jButtonJobInfo.setText("Job Info");
        jButtonJobInfo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonJobInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJobInfoActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonJobInfo);
        jButtonJobInfo.setBounds(20, 330, 180, 70);

        cardframe.setBackground(new java.awt.Color(102, 102, 255));
        cardframe.setLayout(new java.awt.CardLayout());

        jPanelAddressInfo.setBackground(new java.awt.Color(102, 102, 255));

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("COMPANY NAME");

        jTextFieldCompanyName.setNextFocusableComponent(jTextFieldFirstName);

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("FULL NAME");

        jTextFieldFirstName.setForeground(new java.awt.Color(153, 153, 153));
        jTextFieldFirstName.setText("First Name");
        jTextFieldFirstName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldFirstNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldFirstNameFocusLost(evt);
            }
        });

        jComboBoxTitle.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        jComboBoxTitle.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mr", "Mrs", "Miss", "Ms", "Mx", "Sir", "Dr" }));

        jTextFieldMidelName.setForeground(new java.awt.Color(153, 153, 153));
        jTextFieldMidelName.setText("Midel Name");
        jTextFieldMidelName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldMidelNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldMidelNameFocusLost(evt);
            }
        });

        jTextFieldLastName.setForeground(new java.awt.Color(153, 153, 153));
        jTextFieldLastName.setText("Last Name");
        jTextFieldLastName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldLastNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldLastNameFocusLost(evt);
            }
        });

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("JOB TITLE");

        jTextFieldJobTitle.setNextFocusableComponent(jTextFieldContactInfo1);

        jComboBoxContactInfo1.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        jComboBoxContactInfo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Home Phone", "Alt Phone", "Alt Mobile", "Alt Fax", "Main Email", "Alt Email 1", "Alt Email 2", "Linkedin", "Facebook", "Twitter", "Url 1", "Url 2", "Url 3", "Url 4", "Skype ID", "Other 1", "Other 2", "Spouse Work Phone", "Spouse Cell Phone", "Spouse Alternitive Phone" }));

        jTextFieldContactInfo1.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        jTextFieldContactInfo1.setNextFocusableComponent(jTextFieldContactInfoPhone);

        jTextFieldContactInfoPhone.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        jTextFieldContactInfoPhone.setNextFocusableComponent(jTextFieldContactInfoFax);

        jTextFieldContactInfoFax.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        jTextFieldContactInfoFax.setNextFocusableComponent(jTextFieldContactInfoAlternativeContact);

        jTextFieldContactInfoAlternativeContact.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        jTextFieldContactInfoAlternativeContact.setNextFocusableComponent(jTextFieldContactInfoAlternativePhone);

        jTextFieldContactInfoAlternativePhone.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        jTextFieldContactInfoAlternativePhone.setNextFocusableComponent(jTextFieldContactInfoEmail);

        jTextFieldContactInfoEmail.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        jTextFieldContactInfoEmail.setNextFocusableComponent(jTextFieldHouseNumber);

        jPanelAddressDetails.setBackground(new java.awt.Color(238, 193, 73));
        jPanelAddressDetails.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextFieldPOBox.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        jTextFieldPOBox.setNextFocusableComponent(jTextFieldHouseNumber1);
        jPanelAddressDetails.add(jTextFieldPOBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 229, 200, -1));

        jLabel17.setText("P.O.Box");
        jPanelAddressDetails.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 233, -1, -1));

        jLabel16.setText("Zip");
        jPanelAddressDetails.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 202, -1, -1));

        jTextFieldZip.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        jTextFieldZip.setText("9000");
        jTextFieldZip.setNextFocusableComponent(jTextFieldPOBox);
        jPanelAddressDetails.add(jTextFieldZip, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 198, 200, -1));

        jTextFieldRegion.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        jTextFieldRegion.setText("======");
        jTextFieldRegion.setNextFocusableComponent(jTextFieldZip);
        jPanelAddressDetails.add(jTextFieldRegion, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 167, 200, -1));

        jLabel15.setText("Region");
        jPanelAddressDetails.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 171, -1, -1));

        jLabel14.setText("City");
        jPanelAddressDetails.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 137, -1, -1));

        jComboBoxCity.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        jComboBoxCity.setNextFocusableComponent(jTextFieldRegion);
        jComboBoxCity.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jComboBoxCityPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        jPanelAddressDetails.add(jComboBoxCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 133, 200, -1));

        jTextFieldStreetName.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        jTextFieldStreetName.setNextFocusableComponent(jComboBoxCity);
        jPanelAddressDetails.add(jTextFieldStreetName, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 99, 200, -1));

        jLabel18.setText("Street Name");
        jPanelAddressDetails.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 103, -1, -1));

        jLabel19.setText("House Number");
        jPanelAddressDetails.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 72, -1, -1));

        jTextFieldHouseNumber.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        jTextFieldHouseNumber.setNextFocusableComponent(jTextFieldStreetName);
        jPanelAddressDetails.add(jTextFieldHouseNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 68, 200, -1));

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel7.setText("ADDRESS DETAILS");
        jPanelAddressDetails.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        jLabel20.setText("House Number");
        jPanelAddressDetails.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(558, 73, -1, -1));

        jTextFieldHouseNumber1.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        jTextFieldHouseNumber1.setNextFocusableComponent(jTextFieldStreetName1);
        jPanelAddressDetails.add(jTextFieldHouseNumber1, new org.netbeans.lib.awtextra.AbsoluteConstraints(658, 69, 200, -1));

        jLabel21.setText("Street Name");
        jPanelAddressDetails.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(576, 104, -1, -1));

        jTextFieldStreetName1.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        jTextFieldStreetName1.setNextFocusableComponent(jComboBoxCity1);
        jPanelAddressDetails.add(jTextFieldStreetName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(658, 100, 200, -1));

        jLabel22.setText("City");
        jPanelAddressDetails.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(627, 138, -1, -1));

        jComboBoxCity1.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        jComboBoxCity1.setNextFocusableComponent(jTextFieldRegion1);
        jComboBoxCity1.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jComboBoxCity1PopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        jPanelAddressDetails.add(jComboBoxCity1, new org.netbeans.lib.awtextra.AbsoluteConstraints(658, 134, 200, -1));

        jLabel23.setText("Region");
        jPanelAddressDetails.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(609, 171, -1, -1));

        jTextFieldRegion1.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        jTextFieldRegion1.setText("======");
        jTextFieldRegion1.setNextFocusableComponent(jTextFieldZip1);
        jPanelAddressDetails.add(jTextFieldRegion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(658, 167, 200, -1));

        jLabel24.setText("Zip");
        jPanelAddressDetails.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(632, 202, -1, -1));

        jTextFieldZip1.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        jTextFieldZip1.setText("9000");
        jTextFieldZip1.setNextFocusableComponent(jTextFieldPOBox1);
        jPanelAddressDetails.add(jTextFieldZip1, new org.netbeans.lib.awtextra.AbsoluteConstraints(658, 198, 200, -1));

        jLabel25.setText("P.O.Box");
        jPanelAddressDetails.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(604, 233, -1, -1));

        jTextFieldPOBox1.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        jTextFieldPOBox1.setFocusCycleRoot(true);
        jPanelAddressDetails.add(jTextFieldPOBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(658, 229, 200, -1));

        jLabel26.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel26.setText("INVOICE BILL TO");
        jPanelAddressDetails.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 40, -1, -1));

        jLabel27.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel27.setText("SHIP TO");
        jPanelAddressDetails.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(684, 41, -1, -1));

        jButton1.setBackground(new java.awt.Color(143, 145, 121));
        jButton1.setText("COPY =>");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanelAddressDetails.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 50, -1, 89));

        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Phone");

        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Fax");

        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("Alternative Contact");

        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Alternative Phone");

        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("Email");

        javax.swing.GroupLayout jPanelAddressInfoLayout = new javax.swing.GroupLayout(jPanelAddressInfo);
        jPanelAddressInfo.setLayout(jPanelAddressInfoLayout);
        jPanelAddressInfoLayout.setHorizontalGroup(
            jPanelAddressInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAddressInfoLayout.createSequentialGroup()
                .addGroup(jPanelAddressInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAddressInfoLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanelAddressInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelAddressInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jComboBoxContactInfo1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(jLabel29)
                            .addComponent(jLabel30)
                            .addComponent(jLabel31))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelAddressInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelAddressInfoLayout.createSequentialGroup()
                                .addGroup(jPanelAddressInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanelAddressInfoLayout.createSequentialGroup()
                                        .addComponent(jComboBoxTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldFirstName))
                                    .addComponent(jTextFieldCompanyName, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldMidelName, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelAddressInfoLayout.createSequentialGroup()
                                .addGroup(jPanelAddressInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextFieldContactInfoAlternativeContact, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldContactInfoFax, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldContactInfoPhone, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldContactInfo1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldJobTitle, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE))
                                .addGap(46, 46, 46)
                                .addGroup(jPanelAddressInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanelAddressInfoLayout.createSequentialGroup()
                                        .addComponent(jLabel32)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldContactInfoAlternativePhone, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanelAddressInfoLayout.createSequentialGroup()
                                        .addComponent(jLabel33)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldContactInfoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanelAddressInfoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanelAddressDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 907, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(7, Short.MAX_VALUE))
        );
        jPanelAddressInfoLayout.setVerticalGroup(
            jPanelAddressInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAddressInfoLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanelAddressInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextFieldCompanyName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAddressInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTextFieldFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldMidelName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAddressInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jTextFieldJobTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAddressInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAddressInfoLayout.createSequentialGroup()
                        .addGroup(jPanelAddressInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxContactInfo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldContactInfo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelAddressInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldContactInfoPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel29))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelAddressInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldContactInfoFax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel30))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelAddressInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldContactInfoAlternativeContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel31)))
                    .addGroup(jPanelAddressInfoLayout.createSequentialGroup()
                        .addGroup(jPanelAddressInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldContactInfoAlternativePhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel32))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelAddressInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldContactInfoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel33))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelAddressDetails, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                .addContainerGap())
        );

        cardframe.add(jPanelAddressInfo, "card1");

        jPanelPaymentSettings.setBackground(new java.awt.Color(102, 102, 255));

        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("ACCOUNT NO");

        jTextFieldCompanyName1.setNextFocusableComponent(jTextFieldFirstName);

        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("PREFFERED");

        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setText("CREDIT LIMIT");

        jTextFieldCreditLimit.setNextFocusableComponent(jTextFieldFirstName);

        jLabel40.setForeground(new java.awt.Color(255, 255, 255));
        jLabel40.setText("DELIVERY METHOD");

        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setText("PAYMENT METHOD");

        jComboBoxPeferredDeliveryMethod.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "EMAIL", "MAIL", "WHATSAPP" }));

        jLabel43.setForeground(new java.awt.Color(255, 255, 255));
        jLabel43.setText("PREFFERED");

        jComboBoxPeferredPAYMENTMETHOD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "E-WALLET", "BLUE-WALLET", "EASY WALLET", "CASH", "BANK TRANSFER" }));

        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("CREDIT CARD NO:");

        jTextFieldCreditCardNo.setNextFocusableComponent(jTextFieldFirstName);

        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("EXPIRY DATE:");

        jLabel44.setForeground(new java.awt.Color(255, 255, 255));
        jLabel44.setText("CVV");

        jTextFieldCVV.setNextFocusableComponent(jTextFieldFirstName);

        jLabel45.setForeground(new java.awt.Color(255, 255, 255));
        jLabel45.setText("ADDRESS");

        jTextFieldCreditCardAddress.setNextFocusableComponent(jTextFieldFirstName);

        jLabel46.setForeground(new java.awt.Color(255, 255, 255));
        jLabel46.setText("ZIP CODE");

        jTextFieldCreditCardZip.setText("9000");
        jTextFieldCreditCardZip.setNextFocusableComponent(jTextFieldFirstName);

        jLabel47.setForeground(new java.awt.Color(255, 255, 255));
        jLabel47.setText("NAME ON CARD");

        jTextFieldNameOnCard.setNextFocusableComponent(jTextFieldFirstName);

        jMonthChooser1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January ", "February", "March", "April", "May", "June", "July", "August", "September ", "October ", "November ", "December" }));

        javax.swing.GroupLayout jPanelPaymentSettingsLayout = new javax.swing.GroupLayout(jPanelPaymentSettings);
        jPanelPaymentSettings.setLayout(jPanelPaymentSettingsLayout);
        jPanelPaymentSettingsLayout.setHorizontalGroup(
            jPanelPaymentSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPaymentSettingsLayout.createSequentialGroup()
                .addGroup(jPanelPaymentSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPaymentSettingsLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanelPaymentSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPaymentSettingsLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jComboBoxPeferredDeliveryMethod, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52))
                            .addGroup(jPanelPaymentSettingsLayout.createSequentialGroup()
                                .addComponent(jLabel28)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldCompanyName1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelPaymentSettingsLayout.createSequentialGroup()
                                .addComponent(jLabel43)
                                .addGap(44, 44, 44)
                                .addComponent(jComboBoxPeferredPAYMENTMETHOD, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel35)
                            .addComponent(jLabel40)
                            .addComponent(jLabel41))
                        .addGap(86, 86, 86)
                        .addComponent(jLabel37)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldCreditLimit, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelPaymentSettingsLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanelPaymentSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelPaymentSettingsLayout.createSequentialGroup()
                                .addComponent(jLabel47)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldNameOnCard, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelPaymentSettingsLayout.createSequentialGroup()
                                .addComponent(jLabel45)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldCreditCardAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelPaymentSettingsLayout.createSequentialGroup()
                                .addComponent(jLabel46)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldCreditCardZip, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelPaymentSettingsLayout.createSequentialGroup()
                                .addComponent(jLabel44)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldCVV, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelPaymentSettingsLayout.createSequentialGroup()
                                .addComponent(jLabel34)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldCreditCardNo, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelPaymentSettingsLayout.createSequentialGroup()
                                .addComponent(jLabel36)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jMonthChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(jYearChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelPaymentSettingsLayout.setVerticalGroup(
            jPanelPaymentSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPaymentSettingsLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanelPaymentSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(jTextFieldCompanyName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel37)
                    .addComponent(jTextFieldCreditLimit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPaymentSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(jComboBoxPeferredDeliveryMethod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel40)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelPaymentSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel43)
                    .addComponent(jComboBoxPeferredPAYMENTMETHOD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel41)
                .addGap(91, 91, 91)
                .addGroup(jPanelPaymentSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(jTextFieldCreditCardNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPaymentSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jYearChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPaymentSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel36)
                        .addComponent(jMonthChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPaymentSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel47)
                    .addComponent(jTextFieldNameOnCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPaymentSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel44)
                    .addComponent(jTextFieldCVV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPaymentSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCreditCardAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel45))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPaymentSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCreditCardZip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel46))
                .addContainerGap(79, Short.MAX_VALUE))
        );

        cardframe.add(jPanelPaymentSettings, "card2");

        jPanelAdditionalInfo.setBackground(new java.awt.Color(102, 102, 255));

        jLabel9.setText("3");

        javax.swing.GroupLayout jPanelAdditionalInfoLayout = new javax.swing.GroupLayout(jPanelAdditionalInfo);
        jPanelAdditionalInfo.setLayout(jPanelAdditionalInfoLayout);
        jPanelAdditionalInfoLayout.setHorizontalGroup(
            jPanelAdditionalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAdditionalInfoLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel9)
                .addContainerGap(875, Short.MAX_VALUE))
        );
        jPanelAdditionalInfoLayout.setVerticalGroup(
            jPanelAdditionalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAdditionalInfoLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addContainerGap(486, Short.MAX_VALUE))
        );

        cardframe.add(jPanelAdditionalInfo, "card3");

        jPanelJobInfo.setBackground(new java.awt.Color(102, 102, 255));

        jLabel10.setText("4");

        javax.swing.GroupLayout jPanelJobInfoLayout = new javax.swing.GroupLayout(jPanelJobInfo);
        jPanelJobInfo.setLayout(jPanelJobInfoLayout);
        jPanelJobInfoLayout.setHorizontalGroup(
            jPanelJobInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelJobInfoLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel10)
                .addContainerGap(875, Short.MAX_VALUE))
        );
        jPanelJobInfoLayout.setVerticalGroup(
            jPanelJobInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelJobInfoLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addContainerGap(486, Short.MAX_VALUE))
        );

        cardframe.add(jPanelJobInfo, "card4");

        jPanel2.add(cardframe);
        cardframe.setBounds(200, 120, 920, 520);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("CUSTOMER NAME:");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(30, 10, 120, 16);

        jTextFieldOpeningBalance.setText("0");
        jPanel2.add(jTextFieldOpeningBalance);
        jTextFieldOpeningBalance.setBounds(160, 50, 90, 26);
        jPanel2.add(jTextFieldCustomerName);
        jTextFieldCustomerName.setBounds(160, 10, 300, 26);

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("OPENING BALANCE:");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(20, 50, 130, 16);

        jButtonCancel.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jButtonCancel.setText("CANCEL");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonCancel);
        jButtonCancel.setBounds(990, 660, 130, 40);

        jButton3.setBackground(new java.awt.Color(51, 51, 255));
        jButton3.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("OK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);
        jButton3.setBounds(840, 660, 130, 40);

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("SALES REP:");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(790, 20, 70, 16);

        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText("#############################");
        jPanel2.add(jLabel38);
        jLabel38.setBounds(870, 20, 250, 16);

        jPanel1.setBackground(new java.awt.Color(46, 204, 113));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("X");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("New Customer");

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("-");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(473, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(449, 449, 449)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 724, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        int X = evt.getXOnScreen();
        int Y = evt.getYOnScreen();

        this.setLocation(X-mousepX, Y-mousepY);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        mousepX = evt.getX();
        mousepY = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void jButtonJobInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJobInfoActionPerformed
        CardLayout c = (CardLayout)(cardframe.getLayout()); //CardLayout c = (CardLayout)(panel.getLayout());
        c.show(cardframe, "card4");
    }//GEN-LAST:event_jButtonJobInfoActionPerformed

    private void jButtonAddressInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddressInfoActionPerformed
        CardLayout c = (CardLayout)(cardframe.getLayout()); //CardLayout c = (CardLayout)(panel.getLayout());
        c.show(cardframe, "card1");
    }//GEN-LAST:event_jButtonAddressInfoActionPerformed

    private void jButtonPaymentSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPaymentSettingsActionPerformed
        CardLayout c = (CardLayout)(cardframe.getLayout()); //CardLayout c = (CardLayout)(panel.getLayout());
        c.show(cardframe, "card2");
    }//GEN-LAST:event_jButtonPaymentSettingsActionPerformed

    private void jButtonAdditionalInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdditionalInfoActionPerformed
        CardLayout c = (CardLayout)(cardframe.getLayout()); //CardLayout c = (CardLayout)(panel.getLayout());
        c.show(cardframe, "card3");
    }//GEN-LAST:event_jButtonAdditionalInfoActionPerformed

    private void jTextFieldFirstNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldFirstNameFocusGained
        if(jTextFieldFirstName.getText().equals("First Name")){
            jTextFieldFirstName.setText("");
        }
    }//GEN-LAST:event_jTextFieldFirstNameFocusGained

    private void jTextFieldMidelNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldMidelNameFocusGained
        if(jTextFieldMidelName.getText().equals("Midel Name")){
            jTextFieldMidelName.setText("");
        }
    }//GEN-LAST:event_jTextFieldMidelNameFocusGained

    private void jTextFieldLastNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldLastNameFocusGained
        if(jTextFieldLastName.getText().equals("Last Name")){
            jTextFieldLastName.setText("");
        }
    }//GEN-LAST:event_jTextFieldLastNameFocusGained

    private void jTextFieldFirstNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldFirstNameFocusLost
        if(jTextFieldFirstName.getText().equals("")){
            jTextFieldFirstName.setForeground(textColor);//[153,153,153]
            jTextFieldFirstName.setText("First Name");
        }else{
        jTextFieldFirstName.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_jTextFieldFirstNameFocusLost

    private void jTextFieldMidelNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldMidelNameFocusLost
        if(jTextFieldMidelName.getText().equals("")){
            jTextFieldMidelName.setForeground(textColor);//[153,153,153]
            jTextFieldMidelName.setText("Midel Name");
        }else{
        jTextFieldMidelName.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_jTextFieldMidelNameFocusLost

    private void jTextFieldLastNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldLastNameFocusLost
        if(jTextFieldLastName.getText().equals("")){
            jTextFieldLastName.setForeground(textColor);//[153,153,153]
            jTextFieldLastName.setText("Last Name");
        }else{
        jTextFieldLastName.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_jTextFieldLastNameFocusLost

    private void jComboBoxCityPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jComboBoxCityPopupMenuWillBecomeInvisible
        String tmp = (String)jComboBoxCity.getSelectedItem();
        try {
            con = DriverManager.getConnection("jdbc:mysql://192.168.8.158:3306/BargainDatabase","Berend", "kidcoltv6");
        } catch (SQLException ex) {
            Logger.getLogger(newCustomer.class.getName()).log(Level.SEVERE, null, ex);
        }
        String sql = "select * from cities where city=?";
        try {
            pst = con.prepareStatement(sql);
        } catch (SQLException ex) {
            Logger.getLogger(newCustomer.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            pst.setString(1, tmp);
        } catch (SQLException ex) {
            Logger.getLogger(newCustomer.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            rs = pst.executeQuery();
        } catch (SQLException ex) {
            Logger.getLogger(newCustomer.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            if(rs.next()){
                String region = rs.getString("region");
                jTextFieldRegion.setText(region);
            }
        } catch (SQLException ex) {
            Logger.getLogger(newCustomer.class.getName()).log(Level.SEVERE, null, ex);
        }
        try{

        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jComboBoxCityPopupMenuWillBecomeInvisible

    private void jComboBoxCity1PopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jComboBoxCity1PopupMenuWillBecomeInvisible
        String tmp = (String)jComboBoxCity1.getSelectedItem();
        try {
            con = DriverManager.getConnection("jdbc:mysql://192.168.8.158:3306/BargainDatabase","Berend", "kidcoltv6");
        } catch (SQLException ex) {
            Logger.getLogger(newCustomer.class.getName()).log(Level.SEVERE, null, ex);
        }
        String sql = "select * from cities where city=?";
        try {
            pst = con.prepareStatement(sql);
        } catch (SQLException ex) {
            Logger.getLogger(newCustomer.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            pst.setString(1, tmp);
        } catch (SQLException ex) {
            Logger.getLogger(newCustomer.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            rs = pst.executeQuery();
        } catch (SQLException ex) {
            Logger.getLogger(newCustomer.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            if(rs.next()){
                String region = rs.getString("region");
                jTextFieldRegion1.setText(region);
            }
        } catch (SQLException ex) {
            Logger.getLogger(newCustomer.class.getName()).log(Level.SEVERE, null, ex);
        }
        try{

        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jComboBoxCity1PopupMenuWillBecomeInvisible

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jTextFieldHouseNumber1.setText(jTextFieldHouseNumber.getText());
        jTextFieldStreetName1.setText(jTextFieldStreetName.getText());
        jComboBoxCity1.setSelectedItem(jComboBoxCity.getSelectedItem().toString());
        jTextFieldRegion1.setText(jTextFieldRegion.getText());
        jTextFieldZip1.setText(jTextFieldZip.getText());
        jTextFieldPOBox1.setText(jTextFieldPOBox.getText());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonCancelActionPerformed
    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        String first = jTextFieldFirstName.getText();
        String midel = jTextFieldMidelName.getText();
        String last = jTextFieldLastName.getText();
        
        if ("First Name".equals(first)) {
            jTextFieldFirstName.setText("");
        }
        if ("Midel Name".equals(midel)) {
            jTextFieldMidelName.setText("");
        }
        if ("Last Name".equals(last)) {
            jTextFieldLastName.setText("");
        }
        
        try{
             theQuery("INSERT INTO `Customers`(`Name`, `FullName`, `Salutation`, `FirstName`, `MiddleInitial`, `LastName`, `Company`, "
                     + "`Balance`, `CustomerBalance`, `Contact`, `Type`, `Phone`, `Fax`, `AlternateContact`, `AlternatePhone`, `Email`, "
                     + "`CreditCardAddress`, `CreditCardExpMonth`, `CreditCardExpYear`, `CreditCardNameOnCard`, `CreditCardNumber`, `CreditCardPostalCode`, "
                     + "`CreditLimit`, `BillingLine1`, `BillingLine2`, `BillingLine3`, `BillingCity`, `BillingState`, "
                     + "`BillingPoBox`, `ShippingLine1`, `ShippingLine2`, `ShippingLine3`, `ShippingCity`, `ShippingState`, "
                     + "`ShippingPoBox`, `SalesRep`, `PreferredDeliveryMethod`, `PreferredPaymentMethodName`) "
                     //Values
                     + "VALUES ('"+jTextFieldCustomerName.getText()+"',"
                     + "'"+(jTextFieldFirstName.getText()+" "+jTextFieldMidelName.getText()+" "+jTextFieldLastName.getText())+"','"+jComboBoxTitle.getSelectedItem().toString()+"',"
                     + "'"+jTextFieldFirstName.getText()+"','"+jTextFieldMidelName.getText()+"','"+jTextFieldLastName.getText()+"','"+jTextFieldCompanyName.getText()+"',"
                     + "'"+jTextFieldOpeningBalance.getText()+"','"+jTextFieldOpeningBalance.getText()+"','"+jTextFieldContactInfo1.getText()+"','"+jComboBoxContactInfo1.getSelectedItem().toString()+"',"
                     + "'"+jTextFieldContactInfoPhone.getText()+"','"+jTextFieldContactInfoFax.getText()+"','"+jTextFieldContactInfoAlternativeContact.getText()+"','"+jTextFieldContactInfoAlternativePhone.getText()+"',"
                     + "'"+jTextFieldContactInfoEmail.getText()+"','"+jTextFieldCreditCardAddress.getText()+"','"+jMonthChooser1.getSelectedItem().toString()+"','"+jYearChooser1.getYear()+"','"+jTextFieldNameOnCard.getText()+"',"
                     + "'"+jTextFieldCreditCardNo.getText()+"','"+jTextFieldCreditCardZip.getText()+"','"+jTextFieldCreditLimit.getText()+"','"+jTextFieldHouseNumber.getText()+"','"+jTextFieldStreetName.getText()+"',"
                     + "'"+jTextFieldZip.getText()+"','"+jComboBoxCity.getSelectedItem().toString()+"','"+jTextFieldRegion.getText()+"','"+jTextFieldPOBox.getText()+"','"+jTextFieldHouseNumber1.getText()+"',"
                     + "'"+jTextFieldStreetName1.getText()+"','"+jTextFieldZip1.getText()+"','"+jComboBoxCity1.getSelectedItem().toString()+"','"+jTextFieldRegion1.getText()+"','"+jTextFieldPOBox1.getText()+"',"
                     + "'"+jLabel38.getText()+"','"+jComboBoxPeferredDeliveryMethod.getSelectedItem().toString()+"','"+jComboBoxPeferredPAYMENTMETHOD.getSelectedItem().toString()+"')");
             JOptionPane.showMessageDialog(null, "Inserted");
        this.dispose();
         }
        catch(Exception ex){}
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
  public void theQuery(String query){
      Connection con = null;
      Statement st = null;
      try{
          con = DriverManager.getConnection("jdbc:mysql://192.168.8.158:3306/BargainDatabase","Berend", "kidcoltv6");
          st = con.createStatement();
          st.executeUpdate(query);
      }catch(SQLException ex){
          JOptionPane.showMessageDialog(null,ex.getMessage());
          System.out.println(ex.getMessage());
      }
  }
  
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(newCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(newCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(newCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(newCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new newCustomer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cardframe;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonAdditionalInfo;
    private javax.swing.JButton jButtonAddressInfo;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonJobInfo;
    private javax.swing.JButton jButtonPaymentSettings;
    private javax.swing.JComboBox<String> jComboBoxCity;
    private javax.swing.JComboBox<String> jComboBoxCity1;
    private javax.swing.JComboBox<String> jComboBoxContactInfo1;
    private javax.swing.JComboBox<String> jComboBoxPeferredDeliveryMethod;
    private javax.swing.JComboBox<String> jComboBoxPeferredPAYMENTMETHOD;
    private javax.swing.JComboBox<String> jComboBoxTitle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox<String> jMonthChooser1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelAdditionalInfo;
    private javax.swing.JPanel jPanelAddressDetails;
    private javax.swing.JPanel jPanelAddressInfo;
    private javax.swing.JPanel jPanelJobInfo;
    private javax.swing.JPanel jPanelPaymentSettings;
    private javax.swing.JTextField jTextFieldCVV;
    private javax.swing.JTextField jTextFieldCompanyName;
    private javax.swing.JTextField jTextFieldCompanyName1;
    private javax.swing.JTextField jTextFieldContactInfo1;
    private javax.swing.JTextField jTextFieldContactInfoAlternativeContact;
    private javax.swing.JTextField jTextFieldContactInfoAlternativePhone;
    private javax.swing.JTextField jTextFieldContactInfoEmail;
    private javax.swing.JTextField jTextFieldContactInfoFax;
    private javax.swing.JTextField jTextFieldContactInfoPhone;
    private javax.swing.JTextField jTextFieldCreditCardAddress;
    private javax.swing.JTextField jTextFieldCreditCardNo;
    private javax.swing.JTextField jTextFieldCreditCardZip;
    private javax.swing.JTextField jTextFieldCreditLimit;
    private javax.swing.JTextField jTextFieldCustomerName;
    private javax.swing.JTextField jTextFieldFirstName;
    private javax.swing.JTextField jTextFieldHouseNumber;
    private javax.swing.JTextField jTextFieldHouseNumber1;
    private javax.swing.JTextField jTextFieldJobTitle;
    private javax.swing.JTextField jTextFieldLastName;
    private javax.swing.JTextField jTextFieldMidelName;
    private javax.swing.JTextField jTextFieldNameOnCard;
    private javax.swing.JTextField jTextFieldOpeningBalance;
    private javax.swing.JTextField jTextFieldPOBox;
    private javax.swing.JTextField jTextFieldPOBox1;
    private javax.swing.JTextField jTextFieldRegion;
    private javax.swing.JTextField jTextFieldRegion1;
    private javax.swing.JTextField jTextFieldStreetName;
    private javax.swing.JTextField jTextFieldStreetName1;
    private javax.swing.JTextField jTextFieldZip;
    private javax.swing.JTextField jTextFieldZip1;
    private com.toedter.calendar.JYearChooser jYearChooser1;
    // End of variables declaration//GEN-END:variables
}
